# Generated by Django 6.0.4 on 2026-05-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='empleados_asignados',
            field=models.ManyToManyField(blank=True, related_name='turnos_asignados', to='Gestion.empleado'),
        ),
    ]
